[package]
name = "c_sharp"
version = "0.0.0"
edition = "2021"

[lib]
name = "q_compress_ffi"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.132"
q_compress = {version = "0.11", path = "../q_compress" }
