name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: PyO3/maturin-action@v1
      with:
        command: develop
    - name: Install pytest
      run: pip install pytest
    - name: Run tests
      run: pytest -v
