name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    # TODO: there has to be a cleaner way to do this and also add caching
    - name: "create venv"
      run: python -m venv .venv
    - uses: PyO3/maturin-action@v1
      with:
        command: develop
        args: --manifest-path pco_python/Cargo.toml
        sscache: true
    - name: Install test requirements
      run: source .venv/bin/activate && pip install -r pco_python/test_requirements.txt
    - name: Run tests
      run: source .venv/bin/activate && pytest -v --doctest-glob=*.md
