name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --no-deps
    - name: Ensure formatted
      run: cargo fmt --check
